### ISSUE TITLE
想问下后期是否可以支持下TP系的原厂分区

### ISSUE THREAD

**Issue by lwlleo1015** [VIKINGYFY/CloseWRT-CI#3]
7986平台的 TPLINK 官方已经出DEBUG固件了，原厂分区很方便很安全、目前官方OP和immortalwrt都已支持直接刷入
想问下是否后期可以调整下 TP系 的分区；这样不用很麻烦的去刷UBOOT了，因为刷UBOOT很危险 ^_^

**Comment by VIKINGYFY** [comment]
请到237佬的项目里提交，我这项目只负责编译
