### ISSUE TITLE
能否编译京东云一代闭源驱动版本

### ISSUE THREAD

**Issue by happytrudy** [VIKINGYFY/CloseWRT-CI#5]
京东云一代二手只要30买了一个不会编译闭源驱动版本，请大佬出手

**Comment by VIKINGYFY** [comment]
7621？扔了吧，大佬都没适配

**Comment by happytrudy** [comment]
开源的有 闭源的好像有



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年11月11日(周一) 凌晨0:53
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [VIKINGYFY/CloseWRT-CI] 能否编译京东云一代闭源驱动版本 (Issue #5)




 
7621？扔了吧，大佬都没适配
